Rails/CreateTableWithTimestamps:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: true
# if a codebase is on an older version on rails override this in the local rubocop.yml
Rails/HttpPositionalArguments:
  Enabled: true
Rails/LexicallyScopedActionFilter:
  Enabled: false
Rails/Presence:
  Enabled: true
Rails/FilePath:
  EnforcedStyle: arguments
Rails/RequestReferer:
  EnforcedStyle: referrer
# these paths are self explanatory in a Rails context and do not class comments
Style/Documentation:
  Exclude:
    - 'db/migrate/*'
    - 'test/**/*'
    - 'config/application.rb'
    - 'app/policies/*_policy.rb'
    - 'app/helpers/*.rb'
# migrations being a dsl should not worry about method length
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
# environments being a dsl should not worry about block length
Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'
Layout/ExtraSpacing:
  Exclude:
    - 'Gemfile'
Layout/CommentIndentation:
  Exclude:
    - 'Gemfile'
require:
  - rubocop-rails
